### ISSUE TITLE
Unable to load jars with JarSource

### ISSUE THREAD

**Issue by boozaa** [MatteoJoliveau/PlugFace#14]
Hello and thank you for your package.

I'm trying to use PlugFace on a Windows system and i'm faced on problems using 0.7.0.

PluginSources.jarSource() can have a path String or an URI to load so i use URI because path's String throw exceptions:

```
String path = "modules";
URI uri = new File(path).toURI();

PluginManager manager = PluginManagers.defaultPluginManager();
manager.loadPlugins( PluginSources.jarSource( uri ) );
```

I have "modules/IBRss.jar" in place as a class implementing a shared interface and with annotation @Plugin but the manager retrieve nothing:
```
System.out.println( manager.getAllPlugins() );
--> []
```

And when i'm trying to retrieve the plugin class:

```
IrcBotModule module = manager.getPlugin(IrcBotModule.class);
System.out.println( module );
--> null
```

**Comment by MatteoJoliveau** [comment]
Hi, I'm taking a look at this.
Can you confirm that the URI generated by `new File(path).toURI();` is actually pointing to the right directory? If you pass a relative path like you're doing (which is the same than using `PluginSources.jarSource("modules")` it expects the target to be in same directory as the program executing the code.

**Comment by boozaa** [comment]
Passing the path as URI:
'''
new File(path).toURI() -> file:/C:/Users/david/Documents/workspace/IrcBot/modules/
Content of 'modules' folder: 
IBRss-plugin.jar
manager.getAllPlugins() -> []
module -> null
'''

Passing simply "modules":
'''
manager.loadPlugins( PluginSources.jarSource( "modules" ) );
->
Exception in thread "main" java.lang.IllegalArgumentException: Missing scheme
	at java.nio.file.Paths.get(Paths.java:134)
	at org.plugface.core.factory.PluginSources$1.load(PluginSources.java:66)
	at org.plugface.core.impl.DefaultPluginManager.loadPlugins(DefaultPluginManager.java:104)
	at fr.waazaa.apps.irc.bot.Test.main(Test.java:51)

'''
This is because i use URI instead of String.

**Comment by boozaa** [comment]
The PluginSources work well with my URI:

    [PluginSources] jarSource -> /C:/Users/david/Documents/workspace/IrcBot/modules/
    [PluginSources] -> path.getFileName() -> modules
    [PluginSources] jarUrls -> {C:\Users\david\Documents\workspace\IrcBot\modules\IBRss-plugin.jar=file:/C:/Users/david/Documents/workspace/IrcBot/modules/IBRss-plugin.jar}
    [PluginSources] className -> fr.waazaa.apps.ircbot.modules.rss.IBRss
    [PluginSources] plugins.toString() -> [class fr.waazaa.apps.ircbot.modules.rss.IBRss]

**Comment by boozaa** [comment]
In **DefaultPluginManager**

    Collection<Node<?>> nodes = dependencyResolver.resolve(pluginClasses);

return an empty Collection so 

    createPlugin(Node<?> node, Collection<Object> loaded)

returns empty.

**Comment by boozaa** [comment]
My plugin class:

    @Plugin( name = "module" )
    public class IBRss implements IrcBotModule{
    
        @Override
        public String getVersion() {
            return "1.0.0";
        }

        @Override
        public String getAuthor() {
            return "boozaa";
        }

        @Override
        public void onEnable() {
           
        }

        @Override
        public void onDisable() {
            
        }

        @Override
        public String toString() {
            return "IBRss - " + getVersion() + " - " + getAuthor();
        }
    
    

    }

**Comment by MatteoJoliveau** [comment]
Hi @boozaa sorry for the huge delay, apparently this issue could be connected to #15, and a potential fix is available on [JitPack](https://jitpack.io/#matteojoliveau/PlugFace/hotfix~0.7.1-SNAPSHOT). Can you try with this dependency to see if it works for your problem?

If both issues are resolved I will push the patch to Maven Central so the regular dependency can be used instead of JitPack.

**Comment by MatteoJoliveau** [comment]
I'll close this due to inactivity
