### ISSUE TITLE
unable load plugin bug

### ISSUE THREAD

**Issue by tobato** [MatteoJoliveau/PlugFace#15]
with PlugFace 0.7.0 and SpringPluginManager

my plugin like this

```
@Plugin(name = "JpushSMS")
public class JpushSMS implements SmsPusher {

    @Override
    public void pushSMS(String message, String phone) {
       System.out.println("hello jpush");
    }
}
```

![image](https://user-images.githubusercontent.com/2403930/44308859-d1f7f680-a3ef-11e8-868e-50261a3cd931.png)

![image](https://user-images.githubusercontent.com/2403930/44308919-ec7e9f80-a3f0-11e8-996b-33f006f7669c.png)

**Comment by MatteoJoliveau** [comment]
Hello @tobato 
Can you try again using the following package as a dependency and see if it works?
https://jitpack.io/#matteojoliveau/PlugFace/hotfix~0.7.1-SNAPSHOT

**Comment by tobato** [comment]
It works!

**Comment by MatteoJoliveau** [comment]
Awesome!
I'll push version 0.7.1 to Maven with the fix, should be available in a few hours.
Thanks for the report, it was really a silly mistake of mine (didn't even have a test for it, now it does).
Feel free to close the issue after confirming the new Maven version works.

**Comment by tobato** [comment]
There is aother bug in DefaultPluginManager.

```
@Override
    public Collection<Object> loadPlugins(PluginSource source) throws Exception {
        final Collection<Class<?>> pluginClasses = Objects.requireNonNull(source, "Plugin Source cannot be null").load();
        final Collection<Object> loaded = new ArrayList<>();

        if (pluginClasses.isEmpty()) {
            return loaded;
        }

        for (Class<?> pluginClass : pluginClasses) {
            if (pluginClass.getAnnotation(Plugin.class) == null) {
                pluginClasses.remove(pluginClass);
                continue;
            }
            if (context.hasPlugin(pluginClass)) {
                pluginClasses.remove(pluginClass);
            }
        }

        Collection<Node<?>> nodes = dependencyResolver.resolve(pluginClasses);
        createPlugins(nodes, loaded);
        return loaded;
    }
```

`pluginClasses.remove(pluginClass)` in for loop it may cause `ConcurrentModificationException` .

**Comment by MatteoJoliveau** [comment]
Are you loading plugins in different threads?

Can you describe the scenario in which you are calling `loadPlugins()`?

**Comment by tobato** [comment]
when i put a junit.jar into the plugin folder.  😄

**Comment by MatteoJoliveau** [comment]
Ok I'm fixing this in the same patch.

Just for curiosity, why do you need to load junit at runtime?

**Comment by tobato** [comment]
https://stackoverflow.com/questions/8104692/how-to-avoid-java-util-concurrentmodificationexception-when-iterating-through-an

**Comment by tobato** [comment]
I just put a junit.jar file for the first test when i start to test PlugFace..

**Comment by tobato** [comment]
![image](https://user-images.githubusercontent.com/2403930/44344740-04732380-a4c4-11e8-9bda-96af89723607.png)
the url is wrong.

**Comment by MatteoJoliveau** [comment]
PlugFace 0.7.1 is on Maven Central

**Comment by MatteoJoliveau** [comment]
I'll close this at it seems to be resolved. Feel free to open new issues if any problem surface again.

**Comment by tobato** [comment]
thank you!
